import { useEffect, useState } from 'react';
import sb from '../../supabaseClient';
import { useEly } from '../../hooks/useEly';

const box={background:'var(--bg)',border:'1px solid var(--border)',borderRadius:14,padding:16,marginBottom:14};
const input={width:'100%',boxSizing:'border-box',padding:'9px 11px',border:'1px solid var(--border)',borderRadius:8,background:'var(--bg)',color:'var(--text)',fontSize:13};
const btn={border:'1px solid var(--border)',background:'var(--bg2)',color:'var(--text2)',borderRadius:99,padding:'7px 12px',fontSize:12,cursor:'pointer'};
const primary={...btn,background:'var(--blue)',color:'#fff',border:'none',fontWeight:600};
function partyLabel(i){return `Party ${String.fromCharCode(65+i)}`;}
function cleanJson(text=''){try{const s=String(text).replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();return JSON.parse(s);}catch{return null;}}

export default function DisputeResolution({project}){
 const {send,loading:aiLoading}=useEly({surface:'project_chat',projectId:project.id});
 const [caseRow,setCaseRow]=useState(null),[parties,setParties]=useState([]),[evidence,setEvidence]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[brief,setBrief]=useState(null),[error,setError]=useState('');
 const [evidenceForm,setEvidenceForm]=useState({party_id:'',title:'',notes:''});

 const load=async()=>{setLoading(true);setError('');try{let {data:c,error:ce}=await sb.from('dispute_cases').select('*').eq('project_id',project.id).maybeSingle();if(ce)throw ce;if(!c){const {data,error}=await sb.from('dispute_cases').insert({project_id:project.id,title:`Dispute - ${project.site_address||project.bo_premise_address||project.ref||'Project'}`}).select('*').single();if(error)throw error;c=data;}setCaseRow(c);setBrief(c?.case_brief||null);const [{data:p,error:pe},{data:e,error:ee}]=await Promise.all([sb.from('dispute_parties').select('*, dispute_party_people(*)').eq('case_id',c.id).order('sort_order'),sb.from('dispute_evidence').select('*').eq('case_id',c.id).order('created_at')]);if(pe)throw pe;if(ee)throw ee;setParties(p||[]);setEvidence(e||[]);}catch(e){setError(e.message||'Could not load dispute workspace.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[project.id]);

 const addParty=async()=>{if(!caseRow)return;const i=parties.length;const {data,error}=await sb.from('dispute_parties').insert({case_id:caseRow.id,label:partyLabel(i),sort_order:i}).select('*').single();if(error)return setError(error.message);setParties(x=>[...x,{...data,dispute_party_people:[]}]);};
 const patchParty=(id,k,v)=>setParties(ps=>ps.map(p=>p.id===id?{...p,[k]:v}:p));
 const saveParty=async p=>{setSaving(true);const {error}=await sb.from('dispute_parties').update({party_name:p.party_name||null,party_type:p.party_type||null,position_statement:p.position_statement||null,desired_outcome:p.desired_outcome||null,updated_at:new Date().toISOString()}).eq('id',p.id);if(error)setError(error.message);setSaving(false);};
 const removeParty=async p=>{if(!confirm(`Remove ${p.label}?`))return;const {error}=await sb.from('dispute_parties').delete().eq('id',p.id);if(error)return setError(error.message);setParties(ps=>ps.filter(x=>x.id!==p.id));};
 const addPerson=async p=>{const {data,error}=await sb.from('dispute_party_people').insert({party_id:p.id,name:'',sort_order:p.dispute_party_people?.length||0}).select('*').single();if(error)return setError(error.message);setParties(ps=>ps.map(x=>x.id===p.id?{...x,dispute_party_people:[...(x.dispute_party_people||[]),data]}:x));};
 const patchPerson=(pid,id,k,v)=>setParties(ps=>ps.map(p=>p.id===pid?{...p,dispute_party_people:(p.dispute_party_people||[]).map(x=>x.id===id?{...x,[k]:v}:x)}:p));
 const savePerson=async x=>{const {error}=await sb.from('dispute_party_people').update({name:x.name,role:x.role||null,email:x.email||null,phone:x.phone||null}).eq('id',x.id);if(error)setError(error.message);};
 const removePerson=async(pid,id)=>{const {error}=await sb.from('dispute_party_people').delete().eq('id',id);if(error)return setError(error.message);setParties(ps=>ps.map(p=>p.id===pid?{...p,dispute_party_people:p.dispute_party_people.filter(x=>x.id!==id)}:p));};
 const addEvidence=async()=>{if(!caseRow||!evidenceForm.title.trim())return;const {data,error}=await sb.from('dispute_evidence').insert({case_id:caseRow.id,party_id:evidenceForm.party_id||null,title:evidenceForm.title.trim(),notes:evidenceForm.notes.trim()||null}).select('*').single();if(error)return setError(error.message);setEvidence(x=>[...x,data]);setEvidenceForm({party_id:'',title:'',notes:''});};
 const removeEvidence=async id=>{const {error}=await sb.from('dispute_evidence').delete().eq('id',id);if(error)return setError(error.message);setEvidence(x=>x.filter(e=>e.id!==id));};

 const createBrief=async()=>{if(!caseRow)return;setSaving(true);setError('');try{for(const p of parties)await saveParty(p);const payload={project:{id:project.id,reference:project.ref||'',address:project.site_address||project.bo_premise_address||''},parties:parties.map(p=>({label:p.label,name:p.party_name||'',type:p.party_type||'',people:(p.dispute_party_people||[]).map(x=>({name:x.name,role:x.role})),position:p.position_statement||'',outcome_sought:p.desired_outcome||''})),evidence:evidence.map(e=>({party:parties.find(p=>p.id===e.party_id)?.label||'General',title:e.title,notes:e.notes||''}))};
 const prompt=`You are Nora, acting as the private professional assistant to an independent project manager or mediator. Analyse the dispute intake below neutrally. Do not decide who is right, do not invent facts, and distinguish allegations from agreed facts. Return ONLY valid JSON with these keys: executive_summary (string), party_summaries (array of {party,name,position,outcome_sought,key_points}), agreed_or_common_facts (array), disputed_facts (array), financial_claims (array), workmanship_issues (array), programme_delay_issues (array), contractual_issues (array), relationship_communication_issues (array), possible_common_ground (array), missing_information (array), preparation_points (array). Keep it concise and useful to a mediator.\n\nDISPUTE INTAKE:\n${JSON.stringify(payload)}`;
 const result=await send(prompt,{projectId:project.id,mode:'discuss',sessionType:'dispute_preparation',context:{dispute_case_id:caseRow.id,dispute_intake:payload}});const text=result?.response||result?.content||result?.message||result?.text||result;const parsed=cleanJson(typeof text==='string'?text:JSON.stringify(text));if(!parsed)throw new Error('Nora returned a case brief that could not be read as structured data. Please run it again.');setBrief(parsed);const {error}=await sb.from('dispute_cases').update({case_brief:parsed,updated_at:new Date().toISOString()}).eq('id',caseRow.id);if(error)throw error;}catch(e){setError(e.message||'Could not create case brief.');}finally{setSaving(false);}};

 if(loading)return <div style={box}>Loading dispute workspace…</div>;
 return <div style={{maxWidth:1050,margin:'0 auto'}}>
  <div style={box}><div style={{fontSize:18,fontWeight:800,color:'var(--text)'}}>Dispute Resolution</div><div style={{fontSize:13,color:'var(--text3)',marginTop:5}}>Private case preparation for the project manager or mediator. Nora organises the dispute here. Phoenix does not take over until live mediation begins.</div>{error&&<div style={{marginTop:10,padding:10,borderRadius:8,background:'#fef2f2',color:'#b91c1c',fontSize:12}}>{error}</div>}</div>
  <div style={box}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><div style={{fontSize:14,fontWeight:700,color:'var(--text)'}}>Parties</div><div style={{fontSize:12,color:'var(--text3)',marginTop:2}}>Each party can contain an individual, several people, or a company and its representatives.</div></div><button style={btn} onClick={addParty}>+ Add party</button></div></div>
  {parties.length===0&&<div style={{...box,textAlign:'center',color:'var(--text3)'}}>No parties added yet. Add Party A to begin.</div>}
  {parties.map(p=><div key={p.id} style={box}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><div style={{fontWeight:800,color:'var(--text)'}}>{p.label}</div><button style={{...btn,color:'#dc2626'}} onClick={()=>removeParty(p)}>Remove</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,marginBottom:10}}><input style={input} value={p.party_name||''} onChange={e=>patchParty(p.id,'party_name',e.target.value)} placeholder="Party / company name"/><input style={input} value={p.party_type||''} onChange={e=>patchParty(p.id,'party_type',e.target.value)} placeholder="Role e.g. Homeowner / Contractor"/></div><textarea style={{...input,minHeight:150,resize:'vertical',marginBottom:10}} value={p.position_statement||''} onChange={e=>patchParty(p.id,'position_statement',e.target.value)} placeholder="Paste or summarise this party's initial position, claim, response or dispute statement"/><textarea style={{...input,minHeight:72,resize:'vertical'}} value={p.desired_outcome||''} onChange={e=>patchParty(p.id,'desired_outcome',e.target.value)} placeholder="What outcome is this party seeking?"/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:14,marginBottom:8}}><div style={{fontSize:12,fontWeight:700,color:'var(--text2)'}}>People in {p.label}</div><button style={btn} onClick={()=>addPerson(p)}>+ Add person</button></div>{(p.dispute_party_people||[]).map(x=><div key={x.id} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr)) auto',gap:7,marginBottom:7}}><input style={input} value={x.name||''} onBlur={()=>savePerson(x)} onChange={e=>patchPerson(p.id,x.id,'name',e.target.value)} placeholder="Name"/><input style={input} value={x.role||''} onBlur={()=>savePerson(x)} onChange={e=>patchPerson(p.id,x.id,'role',e.target.value)} placeholder="Role"/><input style={input} value={x.email||''} onBlur={()=>savePerson(x)} onChange={e=>patchPerson(p.id,x.id,'email',e.target.value)} placeholder="Email"/><button style={btn} onClick={()=>removePerson(p.id,x.id)}>×</button></div>)}<div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button style={primary} onClick={()=>saveParty(p)}>{saving?'Saving…':'Save party'}</button></div></div>)}
  <div style={box}><div style={{fontSize:14,fontWeight:700,color:'var(--text)',marginBottom:4}}>Supporting material</div><div style={{fontSize:12,color:'var(--text3)',marginBottom:12}}>Register the key documents, emails, reports, photographs or other evidence relied on. The note can contain the relevant extract or a short explanation.</div><div style={{display:'grid',gridTemplateColumns:'minmax(130px,.6fr) minmax(180px,1fr)',gap:8,marginBottom:8}}><select style={input} value={evidenceForm.party_id} onChange={e=>setEvidenceForm(f=>({...f,party_id:e.target.value}))}><option value="">General / both parties</option>{parties.map(p=><option key={p.id} value={p.id}>{p.label}{p.party_name?` - ${p.party_name}`:''}</option>)}</select><input style={input} value={evidenceForm.title} onChange={e=>setEvidenceForm(f=>({...f,title:e.target.value}))} placeholder="Document / evidence title"/></div><textarea style={{...input,minHeight:70,resize:'vertical'}} value={evidenceForm.notes} onChange={e=>setEvidenceForm(f=>({...f,notes:e.target.value}))} placeholder="Relevant extract, summary or note"/><div style={{marginTop:8}}><button style={btn} onClick={addEvidence}>+ Add supporting item</button></div>{evidence.map(e=><div key={e.id} style={{display:'flex',gap:8,alignItems:'flex-start',borderTop:'1px solid var(--border)',paddingTop:9,marginTop:9}}><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:'var(--text)'}}>{parties.find(p=>p.id===e.party_id)?.label||'General'} · {e.title}</div>{e.notes&&<div style={{fontSize:12,color:'var(--text3)',marginTop:3,whiteSpace:'pre-wrap'}}>{e.notes}</div>}</div><button style={{...btn,color:'#dc2626'}} onClick={()=>removeEvidence(e.id)}>Remove</button></div>)}</div>
  <div style={box}><div style={{fontSize:14,fontWeight:700,color:'var(--text)',marginBottom:5}}>Nora Case Brief</div><div style={{fontSize:12,color:'var(--text3)',marginBottom:12}}>Nora V2 reads the positions and supporting material and creates a neutral mediator-facing dispute map. This is preparation, not a judgment.</div><button style={primary} disabled={!parties.length||saving||aiLoading} onClick={createBrief}>{saving||aiLoading?'Nora is reviewing…':brief?'Refresh case brief':'Create case brief'}</button>{brief&&<Brief brief={brief}/>}</div>
  <div style={{...box,border:'1px solid #c7d2fe',background:'#eef2ff'}}><div style={{fontSize:14,fontWeight:800,color:'#3730a3'}}>Live Mediation</div><div style={{fontSize:12,color:'#4f46e5',marginTop:4}}>The case stays with Nora during preparation. Starting mediation will later hand the structured case into Phoenix and create the central session and private breakout rooms.</div><button disabled style={{...btn,marginTop:12,opacity:.55}}>Start Mediation · Phoenix</button><div style={{fontSize:11,color:'#6366f1',marginTop:6}}>Phoenix handoff intentionally remains disabled until the breakout-room layer is connected.</div></div>
 </div>;
}

function Brief({brief}){const sections=[['Agreed / common facts','agreed_or_common_facts'],['Disputed facts','disputed_facts'],['Financial claims','financial_claims'],['Workmanship','workmanship_issues'],['Programme / delay','programme_delay_issues'],['Contractual issues','contractual_issues'],['Relationship / communication','relationship_communication_issues'],['Possible common ground','possible_common_ground'],['Missing information','missing_information'],['Preparation points','preparation_points']];return <div style={{marginTop:16}}>{brief.executive_summary&&<div style={{padding:'12px 0',borderTop:'1px solid var(--border)'}}><div style={{fontSize:12,fontWeight:800,color:'var(--text)',marginBottom:4}}>Executive summary</div><div style={{fontSize:12,color:'var(--text2)',whiteSpace:'pre-wrap'}}>{brief.executive_summary}</div></div>}{(brief.party_summaries||[]).map((x,i)=><div key={i} style={{padding:'12px 0',borderTop:'1px solid var(--border)'}}><div style={{fontSize:12,fontWeight:800,color:'var(--text)'}}>{x.party}{x.name?`: ${x.name}`:''}</div><div style={{fontSize:12,color:'var(--text2)',marginTop:4}}>{x.position}</div>{x.outcome_sought&&<div style={{fontSize:12,color:'var(--text3)',marginTop:4}}><b>Outcome sought:</b> {x.outcome_sought}</div>}{Array.isArray(x.key_points)&&x.key_points.length>0&&<ul style={{fontSize:12,color:'var(--text2)',margin:'6px 0 0 18px'}}>{x.key_points.map((v,j)=><li key={j}>{typeof v==='string'?v:JSON.stringify(v)}</li>)}</ul>}</div>)}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10,marginTop:8}}>{sections.map(([title,key])=>Array.isArray(brief[key])&&brief[key].length>0?<div key={key} style={{padding:12,border:'1px solid var(--border)',borderRadius:10}}><div style={{fontSize:12,fontWeight:800,color:'var(--text)',marginBottom:6}}>{title}</div><ul style={{fontSize:12,color:'var(--text2)',margin:'0 0 0 17px',padding:0}}>{brief[key].map((v,i)=><li key={i} style={{marginBottom:4}}>{typeof v==='string'?v:JSON.stringify(v)}</li>)}</ul></div>:null)}</div></div>;}
